In [2]:
import pandas as pd
df = pd.read_csv('IRIS.csv')
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [6]:
print(df.shape, df.dtypes)

(150, 5) sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [17]:
df.groupby(['species']).agg(
    Average_Sepal_Length = ('sepal_length', 'mean'),
    Standard_Deviation_of_Sepal_Length = ('sepal_length', 'std'),
    Min_Sepal_Length = ('sepal_length', 'min'),
    Max_Sepal_Length = ('sepal_length', 'max'),

    Average_Sepal_Width = ('sepal_width', 'mean'),
    Standard_Deviation_of_Sepal_Width = ('sepal_width', 'std'),
    Min_Sepal_Width = ('sepal_width', 'min'),
    Max_Sepal_Width = ('sepal_width', 'max'),
    
    Average_Petal_Length = ('petal_length', 'mean'),
    Standard_Deviation_of_Petal_Length = ('petal_length', 'std'),
    Min_Petal_Length = ('petal_length', 'min'),
    Max_Petal_Length = ('petal_length', 'max'),
    
    Average_Petal_Width = ('petal_width', 'mean'),
    Standard_Deviation_of_Petal_Width = ('petal_width', 'std'),
    Min_Petal_Width = ('petal_width', 'min'),
    Max_Petal_Width = ('petal_width', 'max'),   
)

,Average_Sepal_Length,Standard_Deviation_of_Sepal_Length,Min_Sepal_Length,Max_Sepal_Length,Average_Sepal_Width,Standard_Deviation_of_Sepal_Width,Min_Sepal_Width,Max_Sepal_Width,Average_Petal_Length,Standard_Deviation_of_Petal_Length,Min_Petal_Length,Max_Petal_Length,Average_Petal_Width,Standard_Deviation_of_Petal_Width,Min_Petal_Width,Max_Petal_Width
species,,,,,,,,,,,,,,,,
Iris-setosa,5.006,0.352490,4.3,5.8,3.418,0.381024,2.3,4.4,1.464,0.173511,1.0,1.9,0.244,0.107210,0.1,0.6
Iris-versicolor,5.936,0.516171,4.9,7.0,2.770,0.313798,2.0,3.4,4.260,0.469911,3.0,5.1,1.326,0.197753,1.0,1.8
Iris-virginica,6.588,0.635880,4.9,7.9,2.974,0.322497,2.2,3.8,5.552,0.551895,4.5,6.9,2.026,0.274650,1.4,2.5

In [15]:
df.groupby(['species'])[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].agg(['mean', 'std', 'min', 'max'])

                sepal_length                     sepal_width                 \
                        mean       std  min  max        mean       std  min
species
Iris-setosa            5.006  0.352490  4.3  5.8       3.418  0.381024  2.3
Iris-versicolor        5.936  0.516171  4.9  7.0       2.770  0.313798  2.0
Iris-virginica         6.588  0.635880  4.9  7.9       2.974  0.322497  2.2

                     petal_length                     petal_width            \
                 max         mean       std  min  max        mean       std
species
Iris-setosa      4.4        1.464  0.173511  1.0  1.9       0.244  0.107210
Iris-versicolor  3.4        4.260  0.469911  3.0  5.1       1.326  0.197753
Iris-virginica   3.8        5.552  0.551895  4.5  6.9       2.026  0.274650


                 min  max
species
Iris-setosa      0.1  0.6
Iris-versicolor  1.0  1.8
Iris-virginica   1.4  2.5

In [19]:
cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df[cols].agg(['mean', 'std', 'min', 'max'])

      sepal_length  sepal_width  petal_length  petal_width
mean      5.843333     3.054000      3.758667     1.198667
std       0.828066     0.433594      1.764420     0.763161
min       4.300000     2.000000      1.000000     0.100000
max       7.900000     4.400000      6.900000     2.500000

In [22]:
data = df[ (df['species']=='Iris-virginica') & (df['sepal_length']>4.5) ].copy()
data

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
106           4.9          2.5           4.5          1.7  Iris-virginica
107           7.3          2.9           6.3          1.8  Iris-virginica
108           6.7          2.5           5.8          1.8  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
110           6.5          3.2           5.1          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
112           6.8          3.0           5.5          2.1  Iris-virginica
113           5.7          2.5           5.0          2.0  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
115           6.4          3.2           5.3          2.3  Iris-virginica
116           6.5          3.0           5.5          1.8  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [25]:
df.groupby(['species']).agg(
    Average_Sepal_Length = ('sepal_length', 'mean'),
    Maximum_Petal_Width = ('petal_width', 'max'),
    Standard_Deviation_of_Sepal_Width = ('sepal_width', 'std')
)

,Average_Sepal_Length,Maximum_Petal_Width,Standard_Deviation_of_Sepal_Width
species,,,
Iris-setosa,5.006,0.6,0.381024
Iris-versicolor,5.936,1.8,0.313798
Iris-virginica,6.588,2.5,0.322497

In [29]:
df2 = df.copy()
df2['petal_ratio'] = df['petal_length'] / df['petal_width']
df2.groupby(['species']).agg(
    Average_Petal_Ratio = ('petal_ratio', 'mean')
)

                 Average_Petal_Ratio
species
Iris-setosa                 7.078000
Iris-versicolor             3.242837
Iris-virginica              2.780662

In [32]:
##...Working on the Titanic Dataset
df = pd.read_csv('Titanic-Dataset.csv')
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [33]:
data = df[ (df['Sex']=='female')  & (df['Fare']>30) ].copy()
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [72]:
total_survived_in_1st_class = len(df[(df['Pclass']==1) & (df['Survived']==1)])
total_survived_in_2nd_class = len(df[(df['Pclass']==2) & (df['Survived']==1)])
total_survived_in_3rd_class = len(df[(df['Pclass']==3) & (df['Survived']==1)])

total_people_in_1st_class = len(df[(df['Pclass']==1)])
total_people_in_2nd_class = len(df[(df['Pclass']==2)])
total_people_in_3rd_class = len(df[(df['Pclass']==3)])

survival_rate_1st_class = (total_survived_in_1st_class / total_people_in_1st_class) * 100
survival_rate_2nd_class = (total_survived_in_2nd_class / total_people_in_2nd_class) * 100
survival_rate_3rd_class = (total_survived_in_3rd_class / total_people_in_3rd_class) * 100


result = df.groupby(['Pclass']).agg(
     Survival_Rate_in_Percentage = ('Survived', 'mean'), # This does the (sum / count) for me !
     Average_Fare = ('Fare', 'mean'),
     Average_Age = ('Age', 'mean')
 )
result['Survival_Rate_in_Percentage'] = result['Survival_Rate_in_Percentage'] * 100

result

        Survival_Rate_in_Percentage  Average_Fare  Average_Age
Pclass
1                         62.962963     84.154687    38.233441
2                         47.282609     20.662183    29.877630
3                         24.236253     13.675550    25.140620

In [ ]:
print(survival_rate_1st_class, survival_rate_2nd_class, survival_rate_3rd_class) # Values match !!

62.96296296296296 47.28260869565217 24.236252545824847