#### Data Transformation -> Feature engineering 
Create a new feature/column based on some values already existing on our data. 
We may need to do this when we 'feel' the need of that feature, but it does not exist in our
original data ####

In [1]:
import pandas as pd
df = pd.read_csv('raw_data.csv')

In [2]:
# Using .apply() for FE.

df2 = df.copy()
# Calculate mean income to fill NaN values in income column.
meanIncome = df2['income'].mean()
print(meanIncome)
df2['income'] = df2['income'].fillna(meanIncome).copy()
# Feature engineering the column - Tax Percentage
# .apply() is a Higher-order-function which takes another function name, or function defn. as its parameter.
df2['tax percentage'] = df2['income'].apply(lambda incm: "20%" if incm >= 62_000 else "10%")
df2['tax amount'] = df2['income'].apply(lambda incm: 0.2*incm if incm>=62_000 else 0.1*incm)
df2

68368.42105263157

,id,name,age,country,gender,income,tax percentage,tax amount
0,1,Rahul Deshmukh,29.0,India,Male,55000.000000,10%,5500.000000
1,1,Rahul Deshmukh,29.0,India,Male,55000.000000,10%,5500.000000
2,2,Ananya Iyer,NaN,India,Female,62000.000000,20%,12400.000000
3,3,Alex Johnson,NaN,USA,Unknown,47000.000000,10%,4700.000000
4,4,Maria Garcia,34.0,Spain,Female,68368.421053,20%,13673.684211
5,5,Li Wei,27.0,China,Male,51000.000000,10%,5100.000000
6,6,NaN,45.0,India,Female,73000.000000,20%,14600.000000
7,7,Ahmed Khan,38.0,NaN,Male,68000.000000,20%,13600.000000
8,8,Rachel Lee,29.0,USA,Female,62000.000000,20%,12400.000000
9,9,Carlos Ruiz,NaN,Mexico,Male,45000.000000,10%,4500.000000
10,10,Emily Davis,31.0,USA,NaN,58000.000000,10%,5800.000000
11,11,Amit Patel,30.0,India,Male,95000.000000,20%,19000.000000
12,11,Amit Patel,30.0,India,Male,95000.000000,20%,19000.000000
13,12,Priya Sharma,NaN,India,Female,68368.421053,20%,13673.684211
14,13,Hans Schmidt,42.0,Germany,Male,82000.000000,20%,16400.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000
16,15,Yuki Tanaka,NaN,Japan,Female,71000.000000,20%,14200.000000
17,16,Fatima Zahra,33.0,Egypt,Female,68368.421053,20%,13673.684211
18,17,NaN,29.0,India,Male,61000.000000,10%,6100.000000
19,18,Arjun Malhotra,35.0,India,Male,120000.000000,20%,24000.000000
20,19,Chloe Dubois,28.0,France,Female,59000.000000,10%,5900.000000
21,20,Vikram Sethi,NaN,India,Male,88000.000000,20%,17600.000000

In [3]:
# Using .map() for FE
gender_map = {
    'Male':'M',
    'Female':'F',
    'Unknown':'U_K'
}
df2['gender'] = df2['gender'].map(gender_map).copy()
df2

,id,name,age,country,gender,income,tax percentage,tax amount
0,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000
1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000
2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000
3,3,Alex Johnson,NaN,USA,U_K,47000.000000,10%,4700.000000
4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211
5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000
6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000
7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000
8,8,Rachel Lee,29.0,USA,F,62000.000000,20%,12400.000000
9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000
10,10,Emily Davis,31.0,USA,NaN,58000.000000,10%,5800.000000
11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000
12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000
13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211
14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000
16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000
17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211
18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000
19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000
20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000
21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000

In [4]:
# Using .assing() and Square Braces notation to manually assign values to a manually made column

# .assign()
df2 = df2.assign(new_income = df2['income'] + df2['tax amount']).copy()
# The 1st parameter of .assing() can't contain Spaces...same rules as python variables.

# Better to go with the below Square Bracket notation if you must have spaces, Descriptive on its own, no copying bla bla needed.
df2['new income'] = df2['income'] + df2['tax amount']

df2

,id,name,age,country,gender,income,tax percentage,tax amount,new_income,new income
0,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
3,3,Alex Johnson,NaN,USA,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
8,8,Rachel Lee,29.0,USA,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
10,10,Emily Davis,31.0,USA,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000
20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000

In [5]:
# .replace(oldValues, newValues)
df2['country'] = df2['country'].replace("USA", "United States").copy()
df2

,id,name,age,country,gender,income,tax percentage,tax amount,new_income,new income
0,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
3,3,Alex Johnson,NaN,United States,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
8,8,Rachel Lee,29.0,United States,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
10,10,Emily Davis,31.0,United States,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000
20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000

#### Data Transformation -> Other operations

In [6]:
# Rename all columns manually.... 
df2.info
df2.columns = ["ID", "Name", "Age", "Country", "Gender", "Income", "Tax", "Tax Amount", "New Income from .assign()", "New Income from Braces Notation"] # Lengths must match !!!
# Rename some column labels only
df2 = df2.rename(columns={"Income":"Salary"}).copy()
# Rename some row labels only
df2 = df2.rename(index={0:"Zeroth Row"}).copy()
df2

,ID,Name,Age,Country,Gender,Salary,Tax,Tax Amount,New Income from .assign(),New Income from Braces Notation
Zeroth Row,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
3,3,Alex Johnson,NaN,United States,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
8,8,Rachel Lee,29.0,United States,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
10,10,Emily Davis,31.0,United States,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000
20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000

In [7]:
# Sort values
df2.sort_values("Salary") # Does not change in place !
df2 = df2.sort_values("Salary").copy() # Sort with respect to Salary values
sorted_data = df2.sort_values(['Salary', 'Age']).copy() # Sort with more than 1 col values-> use Age to sort if Salary of 2 rows are same
sorted_data

,ID,Name,Age,Country,Gender,Salary,Tax,Tax Amount,New Income from .assign(),New Income from Braces Notation
9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
3,3,Alex Johnson,NaN,United States,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
Zeroth Row,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
10,10,Emily Davis,31.0,United States,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
8,8,Rachel Lee,29.0,United States,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000
11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000

In [8]:
# Sort indices -> By default Row Labels are Row indices, so better would be to say Sort using Row Labels. (indices word might be confusing here, indices don't mean True Positions in which they appear, they are actually the Row Labels)
sorted_data = sorted_data.rename(index={"Zeroth Row":0}).copy()
sorted_data1 = sorted_data.sort_index().copy() # 😢 Totally ignores previously done sort values !!!!

# Reset Index to 🔥🔥 persist column order done previously, but reset the indices -> Maintains Row Labels and also maintains previously done sorting according to Column values #🔥🔥
sorted_data2 = sorted_data.reset_index() # Creates a new column named "index" to hold original Index/Label values before resetting index.
# 🩵 Use drop=True, to remove that "index" column
sorted_data3 = sorted_data.reset_index(drop=True)

In [9]:
sorted_data1

,ID,Name,Age,Country,Gender,Salary,Tax,Tax Amount,New Income from .assign(),New Income from Braces Notation
0,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
3,3,Alex Johnson,NaN,United States,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
8,8,Rachel Lee,29.0,United States,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
10,10,Emily Davis,31.0,United States,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000
20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000

In [10]:
sorted_data2

,index,ID,Name,Age,Country,Gender,Salary,Tax,Tax Amount,New Income from .assign(),New Income from Braces Notation
0,9,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
1,3,3,Alex Johnson,NaN,United States,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
2,5,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
3,15,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
4,0,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
5,1,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
6,10,10,Emily Davis,31.0,United States,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
7,20,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
8,18,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
9,8,8,Rachel Lee,29.0,United States,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
10,2,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
11,7,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
12,17,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
13,4,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
14,13,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
15,16,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
16,6,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
17,14,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
18,21,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000
19,11,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
20,12,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
21,19,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000

In [11]:
sorted_data3

,ID,Name,Age,Country,Gender,Salary,Tax,Tax Amount,New Income from .assign(),New Income from Braces Notation
0,9,Carlos Ruiz,NaN,Mexico,M,45000.000000,10%,4500.000000,49500.000000,49500.000000
1,3,Alex Johnson,NaN,United States,U_K,47000.000000,10%,4700.000000,51700.000000,51700.000000
2,5,Li Wei,27.0,China,M,51000.000000,10%,5100.000000,56100.000000,56100.000000
3,14,Siddharth Rao,26.0,India,NaN,52000.000000,10%,5200.000000,57200.000000,57200.000000
4,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
5,1,Rahul Deshmukh,29.0,India,M,55000.000000,10%,5500.000000,60500.000000,60500.000000
6,10,Emily Davis,31.0,United States,NaN,58000.000000,10%,5800.000000,63800.000000,63800.000000
7,19,Chloe Dubois,28.0,France,F,59000.000000,10%,5900.000000,64900.000000,64900.000000
8,17,NaN,29.0,India,M,61000.000000,10%,6100.000000,67100.000000,67100.000000
9,8,Rachel Lee,29.0,United States,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
10,2,Ananya Iyer,NaN,India,F,62000.000000,20%,12400.000000,74400.000000,74400.000000
11,7,Ahmed Khan,38.0,NaN,M,68000.000000,20%,13600.000000,81600.000000,81600.000000
12,16,Fatima Zahra,33.0,Egypt,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
13,4,Maria Garcia,34.0,Spain,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
14,12,Priya Sharma,NaN,India,F,68368.421053,20%,13673.684211,82042.105263,82042.105263
15,15,Yuki Tanaka,NaN,Japan,F,71000.000000,20%,14200.000000,85200.000000,85200.000000
16,6,NaN,45.0,India,F,73000.000000,20%,14600.000000,87600.000000,87600.000000
17,13,Hans Schmidt,42.0,Germany,M,82000.000000,20%,16400.000000,98400.000000,98400.000000
18,20,Vikram Sethi,NaN,India,M,88000.000000,20%,17600.000000,105600.000000,105600.000000
19,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
20,11,Amit Patel,30.0,India,M,95000.000000,20%,19000.000000,114000.000000,114000.000000
21,18,Arjun Malhotra,35.0,India,M,120000.000000,20%,24000.000000,144000.000000,144000.000000

In [12]:
# Ranking -> Create a rank column based on some col values
d3 = df.copy()
d3['Income Ranking'] = d3['income'].rank(ascending=False, method="dense")
d3 = d3.sort_values(['income', 'age'], ascending=False).copy()
d3 = d3.reset_index(drop=True)
d3

    id            name   age  country   gender    income  Income Ranking
0   18  Arjun Malhotra  35.0    India     Male  120000.0             1.0
1   11      Amit Patel  30.0    India     Male   95000.0             2.0
2   11      Amit Patel  30.0    India     Male   95000.0             2.0
3   20    Vikram Sethi   NaN    India     Male   88000.0             3.0
4   13    Hans Schmidt  42.0  Germany     Male   82000.0             4.0
5    6             NaN  45.0    India   Female   73000.0             5.0
6   15     Yuki Tanaka   NaN    Japan   Female   71000.0             6.0
7    7      Ahmed Khan  38.0      NaN     Male   68000.0             7.0
8    8      Rachel Lee  29.0      USA   Female   62000.0             8.0
9    2     Ananya Iyer   NaN    India   Female   62000.0             8.0
10  17             NaN  29.0    India     Male   61000.0             9.0
11  19    Chloe Dubois  28.0   France   Female   59000.0            10.0
12  10     Emily Davis  31.0      USA      NaN   58000.0            11.0
13   1  Rahul Deshmukh  29.0    India     Male   55000.0            12.0
14   1  Rahul Deshmukh  29.0    India     Male   55000.0            12.0
15  14   Siddharth Rao  26.0    India      NaN   52000.0            13.0
16   5          Li Wei  27.0    China     Male   51000.0            14.0
17   3    Alex Johnson   NaN      USA  Unknown   47000.0            15.0
18   9     Carlos Ruiz   NaN   Mexico     Male   45000.0            16.0
19   4    Maria Garcia  34.0    Spain   Female       NaN             NaN
20  16    Fatima Zahra  33.0    Egypt   Female       NaN             NaN
21  12    Priya Sharma   NaN    India   Female       NaN             NaN

In [13]:
# Rearranging columns --> 🍀🍀 PERFECT ORDER 🍀🍀
# 1. Create the Rank
d4 = df.copy()
d4['Income Ranking'] = d4['income'].rank(ascending=False, method="dense")

# 2. Sort the data
d4 = d4.sort_values(['income', 'age'], ascending=False)

# 3. Reset index to clean up the 'jumble'
d4 = d4.reset_index(drop=True)

# 4. Rearrange (This ONLY changes the order of display)
# ⚠️ THIS IS NOT RENAMING !!! AS WE MAY GET CONFUSED FROM EARLIER RENAMINGS, WE USED A COPY FROM THE ORIGINAL DF INSTEAD.
cols_in_order = ["id", "name", "age", "country", "income", "Income Ranking", "gender"]
d4 = d4[cols_in_order].copy()

d4

    id            name   age  country    income  Income Ranking   gender
0   18  Arjun Malhotra  35.0    India  120000.0             1.0     Male
1   11      Amit Patel  30.0    India   95000.0             2.0     Male
2   11      Amit Patel  30.0    India   95000.0             2.0     Male
3   20    Vikram Sethi   NaN    India   88000.0             3.0     Male
4   13    Hans Schmidt  42.0  Germany   82000.0             4.0     Male
5    6             NaN  45.0    India   73000.0             5.0   Female
6   15     Yuki Tanaka   NaN    Japan   71000.0             6.0   Female
7    7      Ahmed Khan  38.0      NaN   68000.0             7.0     Male
8    8      Rachel Lee  29.0      USA   62000.0             8.0   Female
9    2     Ananya Iyer   NaN    India   62000.0             8.0   Female
10  17             NaN  29.0    India   61000.0             9.0     Male
11  19    Chloe Dubois  28.0   France   59000.0            10.0   Female
12  10     Emily Davis  31.0      USA   58000.0            11.0      NaN
13   1  Rahul Deshmukh  29.0    India   55000.0            12.0     Male
14   1  Rahul Deshmukh  29.0    India   55000.0            12.0     Male
15  14   Siddharth Rao  26.0    India   52000.0            13.0      NaN
16   5          Li Wei  27.0    China   51000.0            14.0     Male
17   3    Alex Johnson   NaN      USA   47000.0            15.0  Unknown
18   9     Carlos Ruiz   NaN   Mexico   45000.0            16.0     Male
19   4    Maria Garcia  34.0    Spain       NaN             NaN   Female
20  16    Fatima Zahra  33.0    Egypt       NaN             NaN   Female
21  12    Priya Sharma   NaN    India       NaN             NaN   Female

In [ ]:
#...Task -> Shift ID column to end, # Using List-Comprehension !!
emp = pd.read_csv('raw_data.csv')
# print(emp.columns)
# List comprehension below...
new_cols_order = [col_name for col_name in emp.columns if col_name!='id'] # Exclude ID col
new_cols_order.append(emp.columns[0]) # Append back ID col assuming that it is the 0-th Col Label
# print(new_cols_order)
emp = emp[new_cols_order].copy()
emp

              name   age  country   gender    income  id
0   Rahul Deshmukh  29.0    India     Male   55000.0   1
1   Rahul Deshmukh  29.0    India     Male   55000.0   1
2      Ananya Iyer   NaN    India   Female   62000.0   2
3     Alex Johnson   NaN      USA  Unknown   47000.0   3
4     Maria Garcia  34.0    Spain   Female       NaN   4
5           Li Wei  27.0    China     Male   51000.0   5
6              NaN  45.0    India   Female   73000.0   6
7       Ahmed Khan  38.0      NaN     Male   68000.0   7
8       Rachel Lee  29.0      USA   Female   62000.0   8
9      Carlos Ruiz   NaN   Mexico     Male   45000.0   9
10     Emily Davis  31.0      USA      NaN   58000.0  10
11      Amit Patel  30.0    India     Male   95000.0  11
12      Amit Patel  30.0    India     Male   95000.0  11
13    Priya Sharma   NaN    India   Female       NaN  12
14    Hans Schmidt  42.0  Germany     Male   82000.0  13
15   Siddharth Rao  26.0    India      NaN   52000.0  14
16     Yuki Tanaka   NaN    Japan   Female   71000.0  15
17    Fatima Zahra  33.0    Egypt   Female       NaN  16
18             NaN  29.0    India     Male   61000.0  17
19  Arjun Malhotra  35.0    India     Male  120000.0  18
20    Chloe Dubois  28.0   France   Female   59000.0  19
21    Vikram Sethi   NaN    India     Male   88000.0  20