### The Starting

In [1]:

import pandas as pd

data = {
    'Name': ['Sonu', 'Shanu', 'Rimi', 'Suparna'],
    'Age': [22, 23, 21, 18],
    'City': ['Chennai', 'Bankura', 'Durgapur', 'Bankura']
}

df = pd.DataFrame(data) # Create DataFrame from the dictionary, with labels 0, 1, 2, 3 by default.

df # Display the DataFrame.

      Name  Age      City
0     Sonu   22   Chennai
1    Shanu   23   Bankura
2     Rimi   21  Durgapur
3  Suparna   18   Bankura

#### Series in Pandas → These are the values in a Single column of a Dataframe ()

In [2]:
# Creating Series from simple Python Lists

print("=========== Index Based Access ===========\n")
mySeries = pd.Series(["Sonu", "Shanu", "Mithu", "Suparna", "Rimi"])
print(mySeries)
# By default, Labels ==> Indices, Accessing via INDICES
print(mySeries[0], mySeries[1])
print("\n")


# LABEL based access, Labels are basically Named INDICES. we may use index=LabelList, but it is actually the list of Labels. INDICES directly point to Positions, LABELS point to the Label associated with that position, Named Indices.
print("=========== Label Based Access ===========\n")
myAgeSeries = pd.Series([22, 23, 45, 19], index=['Sonu', 'Shanu', 'Mithu', 'Suparna'])
print(myAgeSeries)
print(myAgeSeries['Mithu'], myAgeSeries['Shanu']) # Accessing via labels

=========== Index Based Access ===========

0       Sonu
1      Shanu
2      Mithu
3    Suparna
4       Rimi
dtype: object
Sonu Shanu


=========== Label Based Access ===========

Sonu       22
Shanu      23
Mithu      45
Suparna    19
dtype: int64
45 23

#### Properties of Series

In [3]:
# ➡️ They are Homogenous, Mix of types result in dtype=OBJECT #

# ➡️ They Support vectorized Operations like NumPy Arrays #
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([100, 200, 300, 400, 500])
sum = s1+s2
sum.index = ['Sum of index-0', 'Sum of index-1', 'Sum of index-2', 'Sum of index-3', 'Sum of index-4']
print(sum)

# ➡️ Mutable Values, ➡️ Immutable Size #
series = pd.Series([1, 2, 3, 4, 5])
# Mutable values #
series[2] = 675
print(series)
# Size is immutable, even if we drop something, it returns a new Series with dropped values, original series size does not change #
new_series = series.drop(2) # The Label = 2, entirely Vanishes !! Labels go as 0,1,3,4 🤪🤪
print(series) 
print(new_series)

# ➡️ Handle Missing values with NaN #
s1 = pd.Series([1, 3, 4]) # Index 3, 4 is missing --> NaN
s2 = pd.Series([1, 2, 3, 4, 5]) # All indices filled, extra filled indices are 3 and 4
print(s1+s2) # 3rd and 4th index becomes NaN

Sum of index-0    101
Sum of index-1    202
Sum of index-2    303
Sum of index-3    404
Sum of index-4    505
dtype: int64
0      1
1      2
2    675
3      4
4      5
dtype: int64
0      1
1      2
2    675
3      4
4      5
dtype: int64
0    1
1    2
3    4
4    5
dtype: int64
0    2.0
1    5.0
2    7.0
3    NaN
4    NaN
dtype: float64

### DataFrames in Pandas → 2D Labelled Arrays, Labels exist for both Rows and Columns

In [4]:
# Creating Dataframes from a List of Pandas Series, from List of dicts already shown firstly !

## Using Uniform labels for every Series ##
rowLabels = ['Index-0', 'Index-1', 'Index-2', 'Index-3']
dataDict1 = {
    'Name': pd.Series(['Sonu', 'Shanu', 'Rimi', 'Suparna'], index=rowLabels),
    'Age': pd.Series([22, 23, 21, 18],index=rowLabels),
    'City': pd.Series(['Chennai', 'Bankura', 'Durgapur', 'Bankura'],index=rowLabels),
    'Favorite Color': pd.Series(['Red', 'Blue', 'Yellow', 'Red'],index=rowLabels)
}

df1 = pd.DataFrame(dataDict1) # Create DataFrame from the dictionary, with labels=rowLabels


## Using Non-Uniform labels for every Series, Pandas UNIONS them all, no error thrown, empty values under a Particular Label gets NaN ## ----> ⚠️ Not Recommended ⚠️
rowLabels1 = ['Zero', 'One', 'Two', 'Three']
rowLabels2 = ['ZERO', 'ONE', 'TWO', 'THREE']

dataDict2 = {
    'Name': pd.Series(['Sonu', 'Shanu', 'Rimi', 'Suparna'], index=rowLabels1),
    'Age': pd.Series([22, 23, 21, 18],index=rowLabels1),
    'City': pd.Series(['Chennai', 'Bankura', 'Durgapur', 'Bankura'],index=rowLabels2),
    'Favorite Color': pd.Series(['Red', 'Blue', 'Yellow', 'Red'],) # GETS DEFAULT INDICES AS LABELS
}

df2 = pd.DataFrame(dataDict2) # Create DataFrame from the dictionary, with labels=rowLabels1, rowLabels2, and one series uses the default indices as Labels

In [5]:
df1 # Pandas does not sort the labels, as all Series uses Same Labels

            Name  Age      City Favorite Color
Index-0     Sonu   22   Chennai            Red
Index-1    Shanu   23   Bankura           Blue
Index-2     Rimi   21  Durgapur         Yellow
Index-3  Suparna   18   Bankura            Red

In [6]:
df2 # Collects all unique labels from every Series (it makes a "Union"). Automatically sorts them alphabetically/numerically by default during that union process if they aren't identical.
# This sorting is automatic !!

          Name   Age      City Favorite Color
ONE        NaN   NaN   Bankura            NaN
One      Shanu  23.0       NaN            NaN
THREE      NaN   NaN   Bankura            NaN
TWO        NaN   NaN  Durgapur            NaN
Three  Suparna  18.0       NaN            NaN
Two       Rimi  21.0       NaN            NaN
ZERO       NaN   NaN   Chennai            NaN
Zero      Sonu  22.0       NaN            NaN
0          NaN   NaN       NaN            Red
1          NaN   NaN       NaN           Blue
2          NaN   NaN       NaN         Yellow
3          NaN   NaN       NaN            Red

In [7]:
# Show the Row Label names --> Indices of the Rows by default
print(df1.index) # RangeIndex(start=0, stop=4, step=1)

# Show the Column Label Names --> The name of the column, the dictionary keys
print(df1.columns) # Index(['Name', 'Age', 'City', 'Favorite Color'], dtype='object')

Index(['Index-0', 'Index-1', 'Index-2', 'Index-3'], dtype='object')
Index(['Name', 'Age', 'City', 'Favorite Color'], dtype='object')

In [8]:
# Creating Dataframes from List of Lists, passing a seperate Column label list
listOfLists = [["Anuj", 9.8, 'EC 101'], ['Sonu', 7.6, 'CS 101'], ['Shashikant', 8, 'ME 202']]
columnLabels = ['Name', 'CGPA', 'Fav Subject Code']

df = pd.DataFrame(listOfLists, columns=columnLabels)
df

         Name  CGPA Fav Subject Code
0        Anuj   9.8           EC 101
1        Sonu   7.6           CS 101
2  Shashikant   8.0           ME 202

In [9]:
# Creating Dataframes from 2D Numpy Arrays
import numpy as np
listOfLists = [["Anuj", 9.8, 'Semiconductors'], ['Sonu', 7.6, 'Object Oriented Programming'], ['Shashikant', 8, 'Mechanical Workshop']]
columnLabels = ['Name', 'CGPA', 'Fav Lab']

two_D_numpy_array = np.array(listOfLists)

df = pd.DataFrame(two_D_numpy_array, columns=columnLabels)

df

         Name CGPA                      Fav Lab
0        Anuj  9.8               Semiconductors
1        Sonu  7.6  Object Oriented Programming
2  Shashikant    8          Mechanical Workshop

#### Loading CSV and JSON files and then convert to DataFrames

In [10]:
# Load from CSV and print
csv_data = pd.read_csv('employee_data.csv')
csv_data

    ID          NAME  AGE          DEPT  SALARY
0  101  Aarav Sharma   28   Engineering   85000
1  102    Sanya Iyer   32         AI/ML  125000
2  103  Vikram Singh   45    Operations   95000
3  104   Meera Reddy   24   Engineering   72000
4  105     Arjun Das   29  Data Science  110000
5  106  Priya Kapoor   35    Management  140000
6  107   Rohan Varma   31         AI/ML  115000
7  108   Sneha Gupta   27        DevOps   88000

In [11]:
# Load from JSON and print
json_data = pd.read_json('employee_data.json')
json_data

    ID          NAME  AGE          DEPT  SALARY
0  101  Aarav Sharma   28   Engineering   85000
1  102    Sanya Iyer   32         AI/ML  125000
2  103  Vikram Singh   45    Operations   95000
3  104   Meera Reddy   24   Engineering   72000
4  105     Arjun Das   29  Data Science  110000
5  106  Priya Kapoor   35    Management  140000
6  107   Rohan Varma   31         AI/ML  115000
7  108   Sneha Gupta   27        DevOps   88000

In [12]:
print(type(csv_data))
print(type(json_data))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

#### Dataframe Methods -> head, tail, sample, info, shape

In [13]:
## 🎰 🎰  DATAFRAME METHODS 🎰 🎰 ##

df = pd.read_csv('employee_data.csv')
df.head() # Top 5 values

    ID          NAME  AGE          DEPT  SALARY
0  101  Aarav Sharma   28   Engineering   85000
1  102    Sanya Iyer   32         AI/ML  125000
2  103  Vikram Singh   45    Operations   95000
3  104   Meera Reddy   24   Engineering   72000
4  105     Arjun Das   29  Data Science  110000

In [14]:
df.head(2) # Top 2 values

    ID          NAME  AGE         DEPT  SALARY
0  101  Aarav Sharma   28  Engineering   85000
1  102    Sanya Iyer   32        AI/ML  125000

In [15]:
df.tail() # Last 5 values

    ID          NAME  AGE          DEPT  SALARY
3  104   Meera Reddy   24   Engineering   72000
4  105     Arjun Das   29  Data Science  110000
5  106  Priya Kapoor   35    Management  140000
6  107   Rohan Varma   31         AI/ML  115000
7  108   Sneha Gupta   27        DevOps   88000

In [16]:
df.tail(2) # Last 2 values

    ID         NAME  AGE    DEPT  SALARY
6  107  Rohan Varma   31   AI/ML  115000
7  108  Sneha Gupta   27  DevOps   88000

In [17]:
df.sample() # Any random value

    ID         NAME  AGE   DEPT  SALARY
6  107  Rohan Varma   31  AI/ML  115000

In [18]:
df.sample(2) # Any random 2 values

    ID          NAME  AGE         DEPT  SALARY
2  103  Vikram Singh   45   Operations   95000
0  101  Aarav Sharma   28  Engineering   85000

In [19]:
df.info() # Summary of Data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   NAME    8 non-null      object
 2   AGE     8 non-null      int64
 3   DEPT    8 non-null      object
 4   SALARY  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes

In [20]:
df.shape # Returns a Tuple of (no. of Rows, no. of Columns)

(8, 5)

In [21]:
df.describe() # Get important statistical info about the NUMERICAL COLUMNS of the Dataframe
# % represents Percentile, if 25% of SALARY is X, then 25% of people has <= salary Rs.X

              ID        AGE         SALARY
count    8.00000   8.000000       8.000000
mean   104.50000  31.375000  103750.000000
std      2.44949   6.435116   22726.636355
min    101.00000  24.000000   72000.000000
25%    102.75000  27.750000   87250.000000
50%    104.50000  30.000000  102500.000000
75%    106.25000  32.750000  117500.000000
max    108.00000  45.000000  140000.000000

In [22]:
df.columns # Print all column labels

Index(['ID', 'NAME', 'AGE', 'DEPT', 'SALARY'], dtype='object')

In [23]:
df.nunique() # Returns number of Unique Values in A column, Currently in our dataset, Everything will be unique, so unique values in those colums = Number of Rows in those Columns, BUT the Department will have 6 unique Values, as some values are repeated.

ID        8
NAME      8
AGE       8
DEPT      6
SALARY    8
dtype: int64

#### Working with Kaggle Datasets, Selecting Data

In [26]:
data = pd.read_csv('globalAirQuality.csv')
df = pd.DataFrame(data)
# df

In [ ]:
# General Prettify function
def show_heading(string):
    print("="*30, end="")
    print(f" {string} ", end="")
    print("="*30)

# Selecting Columns
# Single Column
show_heading("All Cities")
print(df['city'], end="\n\n")
# Multiple Columns -> Pass List of column labels
show_heading("All Cities and their AQI values")
print(df[['city', 'aqi']], end="\n\n")


# Selecting Rows
# .loc[] syntax --> LOC[row_Labels_or_Slices, column_Labels_or_Slices_IF_PROVIDED] 
# .iloc[] syntax --> ILOC[row_Indices_or_Slices, column_Indices_or_Slices_IF_PROVIDED]
# using loc() takes the Labels (Here labels=indices)
show_heading("Using loc[] to select Rows")
print("\nSelecting Row with Label 4 -------->")
print(df.loc[4])
show_heading("Using loc[start, end, step] to slice df")
print("\nSelection Rows with labels 0 to 4, INCLUSIVE !")
print(df.loc[0:4])
# using iloc() takes the True index values, Here labels=indices, but iloc is EXCLUSIVE !
show_heading("Using iloc[] to select Rows")
print("\nSelecting Row with Index 4 -------->")
print(df.iloc[4])
show_heading("Using iloc[start, end, step] to slice df")
print("\nSelection Rows with labels 0 to 4, EXCLUSIVE !")
print(df.iloc[0:4])

============================== All Cities ==============================
0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

============================== All Cities and their AQI values ==============================
           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

============================== Using loc[] to select Rows ==============================

Selecting Row with Label 4 -------->
timestamp      2025-11-04 22:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               21.083
pm10                               66.423
no2                                38.997
so2                                 6.919
o3                                 45.615
co                                  1.085
aqi                                    97
temperature                        13.632
humidity                           76.499
wind_speed                          4.017
Name: 4, dtype: object
============================== Using loc[start, end, step] to slice df ==============================

Selection Rows with labels 0 to 4, INCLUSIVE !
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250
3  2025-11-04 21:25:17.554219      US  New York    40.713    -74.006  30.403
4  2025-11-04 22:25:17.554219      US  New York    40.713    -74.006  21.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783
3   79.951  63.536  7.609  31.369  0.230  158       23.140    89.153
4   66.423  38.997  6.919  45.615  1.085   97       13.632    76.499

   wind_speed
0       3.725
1       8.969
2       9.650
3       8.956
4       4.017
============================== Using iloc[] to select Rows ==============================

Selecting Row with Index 4 -------->
timestamp      2025-11-04 22:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               21.083
pm10                               66.423
no2                                38.997
so2                                 6.919
o3                                 45.615
co                                  1.085
aqi                                    97
temperature                        13.632
humidity                           76.499
wind_speed                          4.017
Name: 4, dtype: object
============================== Using iloc[start, end, step] to slice df ==============================

Selection Rows with labels 0 to 4, EXCLUSIVE !
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250
3  2025-11-04 21:25:17.554219      US  New York    40.713    -74.006  30.403

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783
3   79.951  63.536  7.609  31.369  0.230  158       23.140    89.153

   wind_speed
0       3.725
1       8.969
2       9.650
3       8.956

In [59]:
# Selecting Rows + Columns ---> A Section of the df, using loc[].
df.loc[0:3, ['city', 'aqi', 'temperature']]

       city  aqi  temperature
0  New York  108       18.504
1  New York   90        5.838
2  New York   84       31.833
3  New York  158       23.140

In [63]:
# Selecting Rows + Columns ---> A Section of the df, using iloc[].
# iloc can't take String Values, it needs true Integer values to use as indices !
city_index = df.columns.get_loc('city')
aqi_index = df.columns.get_loc('aqi')
temp_index = df.columns.get_loc('temperature')
df.iloc[0:4, [city_index, aqi_index, temp_index]] # TO match above loc[] results we must use end index as 4 here, to include 3, as iloc[] is EXCLUSIVE

       city  aqi  temperature
0  New York  108       18.504
1  New York   90        5.838
2  New York   84       31.833
3  New York  158       23.140

In [70]:
# Select single scalar value using at() ---> Takes Integer Index values only, for both ROWS and COLS.
df.at[4, 'city']

'New York'

In [69]:
# Select single scalar value using at() ---> Takes true Label values -> Here it is INT for Rows, STRING for cols
df.iat[4, city_index]

'New York'

#### Filtering Data

In [ ]:
df[ df['aqi']>100 ] # Show only those rows with aqi > 100
df[ (df['aqi']>100) & (df['country']=="IN")] # Show only Indian cities with aqi > 100

# Chain Filtered rows with columns next --> To see only specified data about the needed cities
desired_data = df[ (df['aqi']>100) & (df['country']=="IN")][['country', 'city', 'aqi', 'temperature']].copy() # ⚠️⚠️⚠️ Don't forget to make a copy ⚠️⚠️⚠️

desired_data.head()

     country    city  aqi  temperature
6483      IN  Mumbai  104        6.142
6485      IN  Mumbai  123       35.993
6488      IN  Mumbai  105       31.968
6489      IN  Mumbai  104       33.481
6490      IN  Mumbai  130       37.937

In [83]:
print(desired_data.loc[6490], end = "\n\n")
print(desired_data.iloc[4])

country            IN
city           Mumbai
aqi               130
temperature    37.937
Name: 6490, dtype: object

country            IN
city           Mumbai
aqi               130
temperature    37.937
Name: 6490, dtype: object